---
- name: Start Minikube
  become: false
  command: minikube start --driver=docker
  register: minikube_start
  changed_when: "'Done!' in minikube_start.stdout"

- name: Enable metrics-server addon
  become: false
  command: minikube addons enable metrics-server
