{
 "title": "Projet-autoscale",
 "tags": [ "templated" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "25s",
 "panels": [
  {
   "title": "Total number of active resources by pod",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (nodejs_active_resources_total{namespace=\"default\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of total requests received by pod",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (http_requests_total{namespace=\"default\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of active resources by type",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (nodejs_active_resources{namespace=\"default\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration of HTTP requests in seconds by pod",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(pod) (http_request_duration_seconds_count{namespace=\"default\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}