apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app-public
  template:
    metadata:
      labels:
        app: react-app-public
    spec:
      containers:
      - name: react-app-public
        image: ryusid/publicapp-image:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: react-app-public-service
spec:
  selector:
    app: react-app-public
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30002
  type: LoadBalancer 

