apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mynodeapp-monitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mynodeapp   
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default

